# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Don_tBeShy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'RAMAnimatedTabBarController'
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView'
  pod "Alamofire", "~> 4.5"
  pod 'FSCalendar'
  pod 'NVActivityIndicatorView'

  # Pods for Don_tBeShy

end
